#security:
#  oauth2:
#    client:
#      clientId: account-service
#      clientSecret: passw0rd
#      accessTokenUri: http://auth-service:5000/uaa/oauth/token
#      grant-type: client_credentials
#      scope: server

spring:
  data:
    mongodb:
      host: mongo
      username: user
      password: passw0rd
      database: piggymetrics
      port: 6379
  version: account-service-v1.0

server:
  context-path: /accounts
  port: 6000
