spring:
  data:
    mongodb:
      host: ${MONGODB_HOST}
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: ${MONGODB_PORT}

server:
  context-path: /uaa
  port: 5000
