security:
  oauth2:
    client:
      clientId: statistics-service
      clientSecret: ${STATISTICS_SERVICE_PASSWORD}
      accessTokenUri: http://${AUTH_HOST}:${AUTH_PORT}/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: ${MONGODB_HOST}
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: ${MONGODB_PORT}

server:
  context-path: /statistics
  port: 7000

rates:
  url: https://exchangeratesapi.io/api