server:
  port: 8001
  
# mybatis mapper xml 配置
mybatis:
  # mybatis.type-aliases-package：指定domain类的基包，即指定其在*Mapper.xml文件中可以使用简名来代替全类名
  type-aliases-package: cn.com.cqzk.zk.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
    
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@172.16.5.130:1521:ORCL
    username: doc
    password: doc
      
eureka:
  instance:
#    hostname: ${spring.application.name}
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://admin:admin@${spring.cloud.client.ipAddress}:8401/eureka,http://admin:admin@${spring.cloud.client.ipAddress}:8402/eureka,http://admin:admin@${spring.cloud.client.ipAddress}:8403/eureka
      healthcheck:
        enabled: true
      
